### ISSUE TITLE
SN doesn't seem to really work?

### ISSUE THREAD

**Issue by KristofferC** [oxinabox/MagneticReadHead.jl#31]
With this function

```
function gg(x)
    z = :foo
    b = "fdsf"
    q = Expr(:call, sin, 1)
    print(x)
end
```

and a breakpoint on `gg`:

```
julia> @iron_debug gg(2)

Breakpoint Hit: gg(x) in Main at /mnt/c/Users/Kristoffer/Debugging/file.jl:2➧function gg(x)
     z = :foo
     b = "fdsf"

Vars: x
Commands: CC (Continue), SI (Step In), SN (Step Next), SO (Step Out), XX (Abort)
iron>SN
2
```

I assumed I would "to move to the next IR statement" but instead the function returns.

**Comment by oxinabox** [comment]
Your assumption is correct, it should have just advanced you one IR statement.
I'll have to look closer at what is going wrong.

I don't see anything obvious in https://github.com/oxinabox/MagneticReadHead.jl/blob/1837403b6a46ef137865f8181b0d54a91a412283/src/break_action.jl#L79

**Comment by KristofferC** [comment]
This works after restarting Julia.
