### ISSUE TITLE
CodeTracking dependency missing in tagged version

### ISSUE THREAD

**Issue by diegozea** [oxinabox/MagneticReadHead.jl#49]
MagneticReadHead v0.2.1 gives the following error in Julia 1.1:
```
ERROR: LoadError: ArgumentError: Package MagneticReadHead does not have CodeTracking in its dependencies:
- If you have MagneticReadHead checked out for development and have
  added CodeTracking as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with MagneticReadHead
```
`Pkg.resolve()` doesn't solve the problem.

**Comment by oxinabox** [comment]
That is weird because it is there, in v0.2.1: 
https://github.com/oxinabox/MagneticReadHead.jl/blob/v0.2.1/Project.toml#L7

**Comment by diegozea** [comment]
I found that SHA1 in General https://github.com/JuliaRegistries/General/blob/master/M/MagneticReadHead/Versions.toml#L5 is not the same that in the repo:
```
zea@ubuntu:~/0.2.1$ git show-ref --tags
9e815bfbbff5103740e2ea48631b92fecade6587 refs/tags/v0.1.0
6984fb348abffcfecd60105e121e5c68163d485d refs/tags/v0.2.0
0e3064f3885ff7392c4d9081529fd2619f806306 refs/tags/v0.2.1
```

**Comment by oxinabox** [comment]
Weird! Care to make a PR

**Comment by oxinabox** [comment]
Wierd, I will be taggin v0.2.2 shortly which sould fix it

**Comment by diegozea** [comment]
Great! It works now :) Are you using [TagBot](https://github.com/apps/julia-tagbot)?

**Comment by oxinabox** [comment]
yes.

**Comment by KristofferC** [comment]
> I've found that SHA1 in General https://github.com/JuliaRegistries/General/blob/master/M/MagneticReadHead/Versions.toml#L5 is not the same that in the repo:

The one in General is a tree sha, the tag is a commit SHA.
