### ISSUE TITLE
Consider Renaming

### ISSUE THREAD

**Issue by oxinabox** [oxinabox/MagneticReadHead.jl#7]
MagneticReadHead is too long.

Nice reference to Cassette there,
though with #4 and #5 writing and reading will be a thing.
MagneticHead is an option.

Iron is quiet nice,
Iron is notable for being magetic,
and it would be a nice match to Gallium.

**Comment by oxinabox** [comment]
Perhaps more explict:

 - CompiledDebugger
 - JustInTimeDebugger

**Comment by StefanKarpinski** [comment]
Magneto.jl?

**Comment by timholy** [comment]
CompiledDebugger likely won't be unique forever; after we shake the bugs out of JuliaInterpreter, we're likely to add a frame-compiler that essentially performs the same operations that currently get done at runtime.

If you want to get away from the Cassette nomenclature, what about `InstrumentedDebugger` or just `IDebugger` (capitalize that I or you might get contacted by a lawyer :wink:).

**Comment by oxinabox** [comment]
> CompiledDebugger likely won't be unique forever; after we shake the bugs out of JuliaInterpreter, we're likely to add a frame-compiler that essentially performs the same operations that currently get done at runtime.

Uniqueness is not required. (I mean see Debugger.jl, eventually that will not be the only debugger :-P)

**TheOtherDebugger.jl** has a kind of nice ring to it.
And opens up for someone in the future to write **YetAnotherDebugger.jl**

**Comment by StefanKarpinski** [comment]
Debother.jl? :trollface:

**Comment by DNF2** [comment]
TapeHead? Ferrum?

**Comment by christianpeel** [comment]
**IronOut**  has iron (magnetic) in it and the right meaning.

If you use **UnBugger**, then Julia could have a debugger, an unbugger, and a rebugger.

**Comment by oxinabox** [comment]
**IronOut** is pretty good.
I still like **TheOtherDebugger** for its self-deprecating nature.

**Comment by oxinabox** [comment]
It is too late now
