### ISSUE TITLE
Stepping backwards in the debugger

### ISSUE THREAD

**Issue by DilumAluthge** [oxinabox/MagneticReadHead.jl#75]
I've been reading a bit on how [`rr`](https://github.com/mozilla/rr) implements reverse execution. It seems that they first record a trace, and then they replay the trace. During the "replay" phase, you can step forwards and backwards.

Would it be possible to add this functionality to MagneticReadHead?

**Comment by DilumAluthge** [comment]
cc: @oxinabox @vchuravy

**Comment by oxinabox** [comment]
It makes going forward more expensive.
Have to trigger `fork` every command.
Then have to build tools for navigating those forks.

**Comment by vchuravy** [comment]
I think it would make more sense to integrate with `rr` and I would say this is out of scope for MRH.jl 

Doing a fork at each possible execution step could be feasible, but that would be rather fragile and expensive.

**Comment by DilumAluthge** [comment]
It seems like working with `rr` (and maybe eventually having some integration between `rr` and Julia) is the way to go!

**Comment by oxinabox** [comment]
`rr` doesn't work on Mac, so I am unlikely to work on it.
